import Head from "next/head";
import Image from "next/image";
import Cars from "../Components/Cars/Cars";
import Ticket from "../Components/Ticket/Ticket";
import styles from "../styles/Home.module.css";
import "../styles/Home.module.css";
import Preview from "../Components/Preview/Preview";
import LandingPage from "../Components/LandingPage/LandingPage";
import Footer from "../Components/Footer/Footer";
import Form from "../Components/Form/Form";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Form />
			</main>
		</div>
	);
}
